services:
  # Веб-сервер Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  # Сервис PHP-FPM
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php84_app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  # Сервис СУБД PostgreSQL
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user -d my_database"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
